# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa070f04fa2e063391ee5ad5fd970ac1d2e142989d45f6636220e3aa946b49064e052ae79ee1c82413c427caa9f0b6cbd0cac1d22c00b107e5f38ee0df63fe7

test:
  secret_key_base: dad41e50535249f5452c2c59981311f5bad0776122fa6946f229252d7c9a82ce7655439204a76dc6fb71a8d78b8932e0ea67a8ba764375549b061eef5785f14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
